/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as PlotSellingRouteImport } from './routes/plot-selling'
import { Route as LifestyleRouteImport } from './routes/lifestyle'
import { Route as InvestmentConsultingRouteImport } from './routes/investment-consulting'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstructionBuildRouteImport } from './routes/construction-build'
import { Route as ChannelPartnerRouteImport } from './routes/channel-partner'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ArchitectureDesignRouteImport } from './routes/architecture-design'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotSellingRoute = PlotSellingRouteImport.update({
  id: '/plot-selling',
  path: '/plot-selling',
  getParentRoute: () => rootRouteImport,
} as any)
const LifestyleRoute = LifestyleRouteImport.update({
  id: '/lifestyle',
  path: '/lifestyle',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentConsultingRoute = InvestmentConsultingRouteImport.update({
  id: '/investment-consulting',
  path: '/investment-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionBuildRoute = ConstructionBuildRouteImport.update({
  id: '/construction-build',
  path: '/construction-build',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelPartnerRoute = ChannelPartnerRouteImport.update({
  id: '/channel-partner',
  path: '/channel-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureDesignRoute = ArchitectureDesignRouteImport.update({
  id: '/architecture-design',
  path: '/architecture-design',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/architecture-design': typeof ArchitectureDesignRoute
  '/blog': typeof BlogRouteWithChildren
  '/channel-partner': typeof ChannelPartnerRoute
  '/construction-build': typeof ConstructionBuildRoute
  '/contact': typeof ContactRoute
  '/investment-consulting': typeof InvestmentConsultingRoute
  '/lifestyle': typeof LifestyleRoute
  '/plot-selling': typeof PlotSellingRoute
  '/project': typeof ProjectRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/architecture-design': typeof ArchitectureDesignRoute
  '/blog': typeof BlogRouteWithChildren
  '/channel-partner': typeof ChannelPartnerRoute
  '/construction-build': typeof ConstructionBuildRoute
  '/contact': typeof ContactRoute
  '/investment-consulting': typeof InvestmentConsultingRoute
  '/lifestyle': typeof LifestyleRoute
  '/plot-selling': typeof PlotSellingRoute
  '/project': typeof ProjectRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/architecture-design': typeof ArchitectureDesignRoute
  '/blog': typeof BlogRouteWithChildren
  '/channel-partner': typeof ChannelPartnerRoute
  '/construction-build': typeof ConstructionBuildRoute
  '/contact': typeof ContactRoute
  '/investment-consulting': typeof InvestmentConsultingRoute
  '/lifestyle': typeof LifestyleRoute
  '/plot-selling': typeof PlotSellingRoute
  '/project': typeof ProjectRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/architecture-design'
    | '/blog'
    | '/channel-partner'
    | '/construction-build'
    | '/contact'
    | '/investment-consulting'
    | '/lifestyle'
    | '/plot-selling'
    | '/project'
    | '/services'
    | '/admin/login'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/architecture-design'
    | '/blog'
    | '/channel-partner'
    | '/construction-build'
    | '/contact'
    | '/investment-consulting'
    | '/lifestyle'
    | '/plot-selling'
    | '/project'
    | '/services'
    | '/admin/login'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/architecture-design'
    | '/blog'
    | '/channel-partner'
    | '/construction-build'
    | '/contact'
    | '/investment-consulting'
    | '/lifestyle'
    | '/plot-selling'
    | '/project'
    | '/services'
    | '/admin/login'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ArchitectureDesignRoute: typeof ArchitectureDesignRoute
  BlogRoute: typeof BlogRouteWithChildren
  ChannelPartnerRoute: typeof ChannelPartnerRoute
  ConstructionBuildRoute: typeof ConstructionBuildRoute
  ContactRoute: typeof ContactRoute
  InvestmentConsultingRoute: typeof InvestmentConsultingRoute
  LifestyleRoute: typeof LifestyleRoute
  PlotSellingRoute: typeof PlotSellingRoute
  ProjectRoute: typeof ProjectRoute
  ServicesRoute: typeof ServicesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plot-selling': {
      id: '/plot-selling'
      path: '/plot-selling'
      fullPath: '/plot-selling'
      preLoaderRoute: typeof PlotSellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifestyle': {
      id: '/lifestyle'
      path: '/lifestyle'
      fullPath: '/lifestyle'
      preLoaderRoute: typeof LifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-consulting': {
      id: '/investment-consulting'
      path: '/investment-consulting'
      fullPath: '/investment-consulting'
      preLoaderRoute: typeof InvestmentConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction-build': {
      id: '/construction-build'
      path: '/construction-build'
      fullPath: '/construction-build'
      preLoaderRoute: typeof ConstructionBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-partner': {
      id: '/channel-partner'
      path: '/channel-partner'
      fullPath: '/channel-partner'
      preLoaderRoute: typeof ChannelPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture-design': {
      id: '/architecture-design'
      path: '/architecture-design'
      fullPath: '/architecture-design'
      preLoaderRoute: typeof ArchitectureDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ArchitectureDesignRoute: ArchitectureDesignRoute,
  BlogRoute: BlogRouteWithChildren,
  ChannelPartnerRoute: ChannelPartnerRoute,
  ConstructionBuildRoute: ConstructionBuildRoute,
  ContactRoute: ContactRoute,
  InvestmentConsultingRoute: InvestmentConsultingRoute,
  LifestyleRoute: LifestyleRoute,
  PlotSellingRoute: PlotSellingRoute,
  ProjectRoute: ProjectRoute,
  ServicesRoute: ServicesRoute,
  AdminLoginRoute: AdminLoginRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
